- site: Lille
  deployment:
    - { board: IoT-LAB M3, number: 264}
    - { board: Zolertia Firefly, number: 16}
    - { board: Decawave DWM1001, number: 14}
    - { board: "BBC micro:bit", number: 5}
    - { board: Microchip SAMR21, number: 5}
    - { board: ST B-L072Z-LRWAN1, number: 5}

- site: Grenoble
  deployment:
    - { board: IoT-LAB M3, number: 380}
    - { board: IoT-LAB A8-M3, number: 228}

- site: Saclay
  deployment:
    - { board: IoT-LAB M3, number: 12}
    - { board: IoT-LAB A8-M3, number: 155}
    - { board: Microchip SAMR21, number: 15}
    - { board: Microchip SAMR30, number: 3}
    - { board: Arduino Zero, number: 3}
    - { board: ST B-L072Z-LRWAN1, number: 25}
    - { board: Nordic nRF52DK, number: 10}
    - { board: Nordic nRF52840DK, number: 10}
    - { board: Nordic nRF51DK, number: 5}
    - { board: "BBC micro:bit", number: 1}
    - { board: ST B-L475E-IOT01A, number: 10}
    - { board: NXP FRDM-KW41Z, number: 5}
    - { board: nRF52840-MDK, number: 1}
    - { board: nRF52832-MDK, number: 1}
    - { board: Phytec PhyNODE-KW2X, number: 1}
    - { board: LoRa gateway, number: 1}
    - { board: Pycom, number: 5}
    - { board: RTL SDR, number: 3}
    - { board: Decawave DWM1001, number: 10}

- site: Strasbourg
  deployment:
    - { board: IoT-LAB M3, number: 74}
    - { board: IoT-LAB A8-M3, number: 14}
    - { board: Zigduino, number: 82}

- site: Lyon
  deployment:
    - { board: IoT-LAB M3, number: 18}
    - { board: IoT-LAB A8-M3, number: 11}

- site: Paris
  deployment:
    - { board: IoT-LAB M3, number: 69}
    - { board: IoT-LAB A8-M3, number: 62}
