- site: Lille
  deployment:
    - { board: IoT-LAB M3, number: 264}
    - { board: Zolertia Firefly, number: 16}
    - { board: Decawave DWM1001, number: 14}
    - { board: "BBC micro:bit", number: 5}
    - { board: Microchip SAMR21, number: 5}
    - { board: ST B-L072Z-LRWAN1, number: 5}

- site: Grenoble
  deployment:
    - { board: IoT-LAB M3, number: 380}
    - { board: IoT-LAB A8-M3, number: 228}
    - { board: Raspberry Pi 3, number: 5}
    - { board: Microchip SAMR34, number: 2}
    - { board: Nucleo WL55JC, number: 5}

- site: Saclay
  deployment:
    - { board: IoT-LAB M3, number: 12}
    - { board: IoT-LAB A8-M3, number: 115}
    - { board: Microchip SAMR21, number: 15}
    - { board: Microchip SAMR30, number: 3}
    - { board: Arduino Zero, number: 3}
    - { board: ST B-L072Z-LRWAN1, number: 20}
    - { board: Nordic nRF52DK, number: 10}
    - { board: Nordic nRF52840DK, number: 10}
    - { board: ST B-L475E-IOT01A, number: 10}

- site: Strasbourg
  deployment:
    - { board: IoT-LAB A8-M3, number: 14}
    - { board: IoT-LAB M3, number: 64}
    - { board: Pycom, number: 30}
    - { board: OpenMoteB, number: 40}
    - { board: Zigduino, number: 102}

- site: Paris
  deployment:
    - { board: IoT-LAB M3, number: 69}
    - { board: IoT-LAB A8-M3, number: 62}

- site: Toulouse
  deployment:
    - { board: Decawave DWM1001, number: 44}
